version: '3.8'

services:
  db:
    container_name: my-mongo-container
    image: mongo:6.0.13
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DATABASE}
    volumes:
      - ./mongoData:/data/db
    ports:
      - "37017:27017"

